export const investments = [
  {
    category: 'variableIncome',
    label: 'Renda Variável',
    sharesQuantity: 0,
    totalOpeningPosition: 0,
    totalCurrentPosition: 0,
    totalCapitalGain: 0,
    shares: [
      {
        symbol: 'BBAS3',
        updatedAt: '',
        totalQuotas: 17,
        openingPrice: 48.32,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
    ],
  },
  {
    category: 'realStates',
    label: 'Fundos Imobiliários',
    sharesQuantity: 0,
    totalOpeningPosition: 0,
    totalCurrentPosition: 0,
    totalCapitalGain: 0,
    shares: [
      {
        symbol: 'CPTS11',
        updatedAt: '',
        totalQuotas: 56,
        openingPrice: 76.5,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'CVBI11',
        updatedAt: '',
        totalQuotas: 49,
        openingPrice: 88.42,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'KNCR11',
        updatedAt: '',
        totalQuotas: 23,
        openingPrice: 95.44,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'PORD11',
        updatedAt: '',
        totalQuotas: 66,
        openingPrice: 83.93,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'PVBI11',
        updatedAt: '',
        totalQuotas: 43,
        openingPrice: 94.3,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'AIEC11',
        updatedAt: '',
        totalQuotas: 61,
        openingPrice: 60.04,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'BRCR11',
        updatedAt: '',
        totalQuotas: 42,
        openingPrice: 57.75,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'JSRE11',
        updatedAt: '',
        totalQuotas: 35,
        openingPrice: 70.5,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'HGRU11',
        updatedAt: '',
        totalQuotas: 50,
        openingPrice: 122.96,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'HGLG11',
        updatedAt: '',
        totalQuotas: 17,
        openingPrice: 163.41,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      // {
      //   symbol: 'HGLG13',
      //   updatedAt: '',
      //   totalQuotas: 7,
      //   openingPrice: 155.7,
      //   currentPrice: 0,
      //   profitability: 0,
      //   openingPosition: 0,
      //   currentPosition: 0,
      //   capitalGain: 0,
      // },
      {
        symbol: 'HGLG11',
        updatedAt: '',
        totalQuotas: 15,
        openingPrice: 155.7,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'LVBI11',
        updatedAt: '',
        totalQuotas: 29,
        openingPrice: 106.91,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'BRCO11',
        updatedAt: '',
        totalQuotas: 30,
        openingPrice: 102.29,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'PATL11',
        updatedAt: '',
        totalQuotas: 40,
        openingPrice: 62.55,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'RBRF11',
        updatedAt: '',
        totalQuotas: 53,
        openingPrice: 70.2,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'BCIA11',
        updatedAt: '',
        totalQuotas: 36,
        openingPrice: 86.55,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'KFOF11',
        updatedAt: '',
        totalQuotas: 30,
        openingPrice: 82.14,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      {
        symbol: 'XPML11',
        updatedAt: '',
        totalQuotas: 33,
        openingPrice: 101.8,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
      // {
      //   symbol: 'XPML13',
      //   updatedAt: '',
      //   totalQuotas: 4,
      //   openingPrice: 99.6,
      //   currentPrice: 0,
      //   profitability: 0,
      //   openingPosition: 0,
      //   currentPosition: 0,
      //   capitalGain: 0,
      // },
      {
        symbol: 'VISC11',
        updatedAt: '',
        totalQuotas: 23,
        openingPrice: 107.16,
        currentPrice: 0,
        profitability: 0,
        openingPosition: 0,
        currentPosition: 0,
        capitalGain: 0,
      },
    ],
  },
];
